name: Publish Docker and Helm Chart

on:
  push:
    branches:
      - publish-chart

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/infinite-scroll:latest

      - name: Package Helm chart
        run: helm package ./infinite-scroll-chart

      - name: push to gh-pages
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          ls -lrta
          git add .
          git commit -m "publishing the chart"
          git checkout gh-pages
          git merge --no-ff publish-chart 
          git push origin gh-pages
