name: Publish Docker and Helm Chart

on:
  push:
    branches:
      - publish-chart

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/infinite-scroll:latest

      - name: Setup-git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Package Helm chart
        run: |
          git checkout gh-pages
          git merge --no-ff publish-chart 
          rm *.tgz
          helm package ./infinite-scroll-chart
          helm repo index .
          git add .
          git commit -m "publishing the chart version 0.1.1"
          ls -lrta
          git push origin gh-pages
